before:
  hooks:
    - go mod download
builds:
  -
    id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static" -X github.com/netflix/weep/version.Version={{.Version}} -X github.com/netflix/weep/version.Commit={{.CommitDate}} -X github.com/netflix/weep/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
  -
    id: demo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static" -X github.com/netflix/weep/config.EmbeddedConfigFile=/weep-demo.yaml -X github.com/netflix/weep/version.Version={{.Version}} -X github.com/netflix/weep/version.Commit={{.CommitDate}} -X github.com/netflix/weep/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  -
    builds:
      - default
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
  ids:
    - default
dockers:
  -
    goos: linux
    goarch: amd64
    ids:
      - default
    image_templates:
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:latest"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:{{ .Tag }}"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:v{{ .Major }}"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "public.ecr.aws/consoleme/{{.ProjectName}}:latest"
      - "public.ecr.aws/consoleme/{{.ProjectName}}:{{ .Tag }}"
      - "public.ecr.aws/consoleme/{{.ProjectName}}:v{{ .Major }}"
      - "public.ecr.aws/consoleme/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
blobs:
  -
    provider: s3
    bucket: consolemeoss
    region: us-west-2
    folder: "consolemeoss_deploy/weep_binaries/{{.Version}}/"
