consoleme_url: https://path_to_consoleme:port
authentication_method: challenge|mtls
# mtls_settings:
#   cert: /path/to/your/cert
#   key: /path/to/your/key
#   cafile: /path/to/your/cafile
#   insecure: true|false
metadata:
  routes:
    - path: latest/user-data
    - path: latest/meta-data/local-ipv4
      data: "127.0.0.1"
    - path: latest/meta-data/local-hostname
      data: ip-127-0-0-1.us-west-2.compute.internal
